config/routes.rb
Rails.application.routes.draw do
  get 'templates/serve'

  get '/home' => 'static_pages#home'
  get '/templates/:name' => "templates#serve", as: 'template'
  get '/profile/:id' => "users#profile", as: 'profile'
  post '/ban' => 'users#ban', as: 'ban'
  devise_for :users
  root 'static_pages#data'
  resources :items do
    resources :images
  end
  resources :projections, only: :create
end

app/models/image.rb
class Image < ActiveRecord::Base
  belongs_to :item
  has_attached_file :picture, :styles => { :large => "x400", :medium => "x300", :thumb => "x100" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :picture, :content_type => /\Aimage\/.*\Z/
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :set_image, only: [:show, :edit, :update, :destroy]

  # GET /images
  # GET /images.json
  def index
    @images = Image.all
  end

  # GET /images/1
  # GET /images/1.json
  def show
  end

  # GET /images/new
  def new
    @image = Image.new
  end

  # GET /images/1/edit
  def edit
  end

  # POST /images
  # POST /images.json
  def create
    @image = Image.new(image_params)

    respond_to do |format|
      if @image.save
        format.html { redirect_to @image, notice: 'Image was successfully created.' }
        format.json { render :show, status: :created, location: @image }
      else
        format.html { render :new }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /images/1
  # PATCH/PUT /images/1.json
  def update
    respond_to do |format|
      if @image.update(image_params)
        format.html { redirect_to @image, notice: 'Image was successfully updated.' }
        format.json { render :show, status: :ok, location: @image }
      else
        format.html { render :edit }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /images/1
  # DELETE /images/1.json
  def destroy
    @image.destroy
    respond_to do |format|
      format.html { redirect_to images_url, notice: 'Image was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_image
      @image = Image.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def image_params
      params[:image]
    end
end

app/views/images/_form.html.haml
= simple_form_for(@image) do |f|
  = f.error_notification

  .form-inputs

  .form-actions
    = f.button :submit

app/views/images/edit.html.haml
%h1 Editing image

= render 'form'

= link_to 'Show', @image
\|
= link_to 'Back', images_path

app/views/images/index.html.haml
%h1 Listing images

%table
  %tr
    %th
    %th
    %th

  - @images.each do |image|
    %tr
      %td= link_to 'Show', image
      %td= link_to 'Edit', edit_image_path(image)
      %td= link_to 'Destroy', image, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Image', new_image_path

app/views/images/new.html.haml
%h1 New image

= render 'form'

= link_to 'Back', images_path

app/views/images/show.html.haml
%p#notice= notice


= link_to 'Edit', edit_image_path(@image)
\|
= link_to 'Back', images_path