config/routes.rb
Rails.application.routes.draw do
  get 'templates/serve'

  get '/home' => 'static_pages#home'
  get '/templates/:name' => "templates#serve", as: 'template'
  get '/profile/:id' => "users#profile", as: 'profile'
  post '/ban' => 'users#ban', as: 'ban'
  devise_for :users
  root 'static_pages#data'
  resources :items do
    resources :images
  end
  resources :projections, only: :create
end

app/views/layouts/_head.html.haml
%head
  %meta(charset="utf-8")
  %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
  %meta(name="viewport" content="width=device-width, initial-scale=1.0")
  %title= content_for?(:title) ? yield(:title) : "Weekly"
  = csrf_meta_tags
  / Le HTML5 shim, for IE6-8 support of HTML elements
  /[if lt IE 9]
    = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
  = stylesheet_link_tag "application", :media => "all"
  = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
  = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
  = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
  = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
  = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
  = stylesheet_link_tag "//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.min.css"
  = javascript_include_tag "https://ajax.googleapis.com/ajax/libs/angularjs/1.3.0-rc.4/angular.min.js"
  = javascript_include_tag "https://ajax.googleapis.com/ajax/libs/angularjs/1.3.0-rc.4/angular-resource.min.js"
  = javascript_include_tag "https://ajax.googleapis.com/ajax/libs/angularjs/1.3.0-rc.4/angular-route.min.js"
  = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/angular-ui-bootstrap/0.10.0/ui-bootstrap-tpls.min.js"
  = javascript_include_tag "application"

app/views/layouts/_navbar.html.haml
.navbar.navbar-default.navbar-static-top.bg-inner
  .container
    %button.navbar-toggle(type="button" data-toggle="collapse" data-target=".navbar-responsive-collapse")
      %span.icon-bar
      %span.icon-bar
      %span.icon-bar
    = link_to "Pricetimate", root_path, class: "navbar-brand"
    .navbar-collapse.collapse.navbar-responsive-collapse
      %ul.nav.navbar-nav
        -if current_user
          %li= link_to "My Profile", profile_path(current_user)
          %li= link_to "Create New Item", new_item_path
        %li= link_to "Items", "/#/items"
        %li.dropdown.pull-right
          %a.btn-btn-default.dropdown-toggle{id:"dropdownMenu1", "data-toggle"=> 'dropdown'}
            Profile Options
            %b.caret
          %ul.dropdown-menu.dropdown-menu-right{role:'menu', 'aria-labelledby'=>"dropdownMenu1"}
            - if current_user
              / Signed in
              %li= link_to "Edit Account", edit_user_registration_path
              %li= link_to "Log out", destroy_user_session_path, method: :delete
            - else
              / Not signed in
              %li= link_to "Log in", new_user_session_path
              %li= link_to "Sign up", new_user_registration_path

app/views/layouts/application.html.haml
!!! 5
%html{'ng-app'=>'itemApp'}
  %base(href='/')
  = render 'layouts/head'
  %body.bg-outer
    .container
      .row
        .bg-inner.round
          =render 'layouts/navbar'
          = bootstrap_flash
          = yield
      %footer
        %p &copy; Company 2014